---
actions:
  to: kubernetes/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{artifact-id}}
  name: {{artifact-id}}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{artifact-id}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{artifact-id}}
    spec:
      containers:
      - image: {{artifact-id}}:{{artifact-version}}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/info
            port: 8080
        name: app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080



